[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "swot-reservoir-wse"
version = "0.3.0"

description = "Generate reservoir-specific Water Surface Elevation (WSE) time series from SWOT LakeSP and PIXC observations."

readme = "README.md"
requires-python = ">=3.10"

license = "MIT"
license-files = ["LICENSE"]

authors = [
    { name = "Ongkar Dasgupta" }
]

keywords = [
    "reservoir",
    "water surface elevation",
    "SWOT",
    "LakeSP",
    "PIXC",
    "pixel cloud",
    "remote sensing",
    "hydrology",
    "earth observation"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Hydrology"
]

dependencies = [
    "earthaccess",
    "earthengine-api",
    "geemap",
    "geopandas",
    "matplotlib",
    "numpy",
    "pandas",
    "tqdm",
    "fiona",
    "pyproj",
    "shapely",
    "xarray",
    "h5netcdf"
]


[project.scripts]
swot-reservoir-wse = "swot_wse.cli:main"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
include = ["swot_wse*"]
exclude = [
    "cache*",
    "data*",
    "build*",
    "downloads*",
    "outputs*",
    "tests*"
]
